const Deptos = [
  {
    value: "01",
    label: "Atlántida",
    municipios: [
      { value: "0101", label: "La Ceiba" },
      { value: "0102", label: "El Porvenir" },
      { value: "0103", label: "Esparta" },
      { value: "0104", label: "Jutiapa" },
      { value: "0105", label: "La Masica" },
      { value: "0106", label: "San Francisco" },
      { value: "0107", label: "Tela" },
      { value: "0108", label: "Arizona" },
    ],
  },
  {
    value: "02",
    label: "Colon",
    municipios: [
      { value: "0201", label: "Trujillo" },
      { value: "0202", label: "Balfate" },
      { value: "0203", label: "Iriona" },
      { value: "0204", label: "Limón" },
      { value: "0205", label: "Sabá" },
      { value: "0206", label: "Santa Fe" },
      { value: "0207", label: "Santa Rosa de Aguán" },
      { value: "0208", label: "Sonaguera" },
      { value: "0209", label: "Tocoa" },
      { value: "0210", label: "Bonito Oriental" },
    ],
  },
  {
    value: "03",
    label: "Comayagua",
    municipios: [
      { value: "0301", label: "Comayagua" },
      { value: "0302", label: "Ajuterique" },
      { value: "0303", label: "El Rosario" },
      { value: "0304", label: "Esquías" },
      { value: "0305", label: "Humuya" },
      { value: "0306", label: "La Libertad" },
      { value: "0307", label: "Lamaní" },
      { value: "0308", label: "La Trinidad" },
      { value: "0309", label: "Lejamaní" },
      { value: "0310", label: "Meámbar" },
      { value: "0311", label: "Minas de Oro" },
      { value: "0312", label: "Ojos de Agua" },
      { value: "0313", label: "San Jerónimo" },
      { value: "0314", label: "San José de Comayagua" },
      { value: "0315", label: "San José del Potrero" },
      { value: "0316", label: "San Luis" },
      { value: "0317", label: "San Sebastián" },
      { value: "0318", label: "Siguatepeque" },
      { value: "0319", label: "Villa de San Antonio" },
      { value: "0320", label: "Las Lajas" },
      { value: "0321", label: "Taulabé" },
    ],
  },
  {
    value: "04",
    label: "Copan",
    municipios: [
      { value: "0401", label: "Santa Rosa de Copán" },
      { value: "0402", label: "Cabañas" },
      { value: "0403", label: "Concepción" },
      { value: "0404", label: "Copán Ruinas" },
      { value: "0405", label: "Corquín" },
      { value: "0406", label: "Cucuyagua" },
      { value: "0407", label: "Dolores" },
      { value: "0408", label: "Dulce Nombre" },
      { value: "0409", label: "El Paraíso" },
      { value: "0410", label: "Florida" },
      { value: "0411", label: "La Jigua" },
      { value: "0412", label: "La Unión" },
      { value: "0413", label: "Nueva Arcadia" },
      { value: "0414", label: "San Agustín" },
      { value: "0415", label: "San Antonio" },
      { value: "0416", label: "San Jerónimo" },
      { value: "0417", label: "San José" },
      { value: "0418", label: "San Juan de Opoa" },
      { value: "0419", label: "San Nicolás" },
      { value: "0420", label: "San Pedro" },
      { value: "0421", label: "Santa Rita" },
      { value: "0422", label: "Trinidad de Copán" },
      { value: "0423", label: "Veracruz" },
    ],
  },
  {
    value: "09",
    label: "Gracias a Dios",
    municipios: [
      { value: "0901", label: "Puerto Lempira" },
      { value: "0902", label: "Brus Laguna" },
      { value: "0903", label: "Ahuas" },
      { value: "0904", label: "Juan Francisco Bulnes" },
      { value: "0905", label: "Ramón Villeda Morales" },
      { value: "0906", label: "Wampusirpe" },
    ],
  },
];

export default Deptos;
